---
exclude: '^$'
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
        name: "Executable text files have shebangs"
      - id: trailing-whitespace
        name: Trailing whitespace (XML)
        types: [xml]
      - id: trailing-whitespace
        name: Trailing whitespace (YAML)
        types: [yaml]
      - id: trailing-whitespace
        name: Trailing whitespace (Markdown)
        types: [markdown]
      - id: check-yaml
        args:
          - "-m"

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.20.0
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
      - id: markdownlint
        types: [markdown]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "1.11.2"
    hooks:
      - id: script-must-have-extension
      - id: shellcheck
        name: shellcheck(linter)
        types: [shell]

  - repo: git@github.com:RedHatTraining/xmlformat.git
    rev: '0.4'
    hooks:
      - id: xmlformat_ruby
        types: [xml]
        args:
          - "-f"
          - xmlformat.conf

  - repo: git@github.com:RedHatTraining/xpath-validation.git
    rev: v0.1.1
    hooks:
      - id: invalid-tags
        files: guides/en-US/.*
        exclude: guides/en-US/Common/.*

  - repo: git@github.com:RedHatTraining/curriculum-tools.git
    rev: v0.1.3
    hooks:
      - id: unsupported-tags-check
        # Try to remove exclude clause after skeleton is
        # compliant with v2.0 of DocBook standard
        types: [xml]
      - id: pattern-warning
        types: [xml]
        exclude: guides/en-US/Common/.*

  - repo: git@github.com:RedHatTraining/pattern-replacer.git
    rev: v0.2
    hooks:
      - id: pattern-replacer
        args:
          - "-s"
          - "P015,P020,P021,P022,P023"
        files: guides/en-US/.*

  - repo: local
    hooks:
      - id: forbidden-files
        name: Forbid entity files other than common.ent
        entry: Only guides/<lang-code>/common.ent entity files are allowed.
        language: fail
        files: 'guides/(?!..-..(_..)?\/common).*\.ent'

  - repo: git@github.com:RedHatTraining/curriculum-tools.git
    rev: v0.1.3
    hooks:
      - id: link-checker
        files: guides/en-US/sg-chapters/topics/.*xml$
      - id: sg-build-check
        files: guides/en-US/((Common/)?|sg-chapters/(topics/[-\w_]+/)?)[-\w_]+[.]xml$
        exclude: guides/en-US/\w+-(EA|IG).xml
      - id: ig-build-check
        exclude: guides/en-US/\w+-EA.xml
        files: guides/en-US/([is]g-chapters/(topics/[-\w_]+/)?)?[-\w_]+[.]xml$
      - id: ea-build-check
        files: guides/en-US/[-\w_]+-EA.xml$|guides/en-US/ea-stubs/[-\w_]+.xml$

